---
- name: Install Clickhouse
  hosts: clickhouse
  become: true
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  become: true
  roles:
    - vector

- name: Install Lighthouse
  hosts: lighthouse
  become: true
  pre_tasks:
    - name: Install git
      ansible.builtin.apt:
        name: git
        update_cache: yes
        state: latest
    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: yes
        state: latest
  roles:
    - lighthouse