---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse
  
  - src: git@github.com:RiteHist/vector-role.git
    scm: git
    version: "1.0"
    name: vector