- name: Install vector
  hosts: vector
  tasks:
    - name: Add Vector repo
      become: true
      ansible.builtin.shell: bash -c "$(curl -L https://setup.vector.dev)"
    - name: Install Vector
      become: true
      ansible.builtin.apt:
        name: vector